config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :wedding_toppings, :path => 'cupulas'

  root 'pages#home'
  resources :cakes, :path => 'productos' do
    get :autocomplete_tag_name, :on => :collection
  end

  get 'buscar'       =>   'cakes#search', as: :search
  get 'catalogo'     =>   'cakes#catalog', as: :catalog
  get 'despacho'     =>   'pages#delivery', as: :delivery
  get 'prensa'       =>   'pages#press', as: :press
  get 'empresas'     =>   'pages#companies', as: :companies
  get 'comprar'      =>   'pages#buy', as: :buy
  get 'sabores'      =>   'pages#flavours', as: :flavours
  get 'ubicacion'    =>   'pages#location', as: :location
  get 'nosotros'     =>   'pages#us', as: :us
end

app/views/layouts/_catalog_header.html.erb
<h1><%= @title %></h1>
<hr class="sep"/>
<div class="actions">
  <%= link_to 'Tortas Decoradas', cakes_url(menu: 'decoradas'), class: 'btn' %>
  <%= link_to 'Tortas de Novios', cakes_url(menu: 'novios'), class: 'btn' %>
  <%= link_to 'Tortas Tradicionales', cakes_url(menu: 'tradicionales'), class: 'btn' %>
  <%= link_to 'Cupcakes', cakes_url(menu: 'cupcakes'), class: 'btn' %>
  <%= link_to 'Cóctel', cakes_url(menu: 'coctel'), class: 'btn' %>
  <%= link_to 'Postres', cakes_url(menu: 'postres'), class: 'btn' %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="footer__items">
    <div class="footer__item">
      <h4 class="footer-item__header">Art-Torta</h4>
      <hr class="sep sep--light sep--thin"/>
      <ul>
        <li>
          <%= link_to 'Catálogo', catalog_url %>
        </li>
        <li>
          <%= link_to 'Comprar', buy_url %>
        </li>
        <li>
          <%= link_to 'Despacho', delivery_url %>
        </li>
        <li>
          <%= link_to 'Sabores', flavours_url %>
        </li>
        <li>
          <%= link_to 'Cúpulas', wedding_toppings_url %>
        </li>
        <li>
          <%= link_to 'Empresas', companies_url %>
        </li>
        <li>
          <%= link_to 'Prensa', press_url %>
        </li>
        <li>
          <%= link_to 'Ubicación', location_url %>
        </li>
        <li>
          <%= link_to 'Nosotros', us_url %>
        </li>
      </ul>
    </div>
    <div class="footer__item">
      <h4 class="footer-item__header">Contacto</h4>
      <hr class="sep sep--light sep--thin"/>
      <ul>
        <li>Dirección:</li>
        <li>Manzano 551, Recoleta</li>
        <li>E-mail:</li>
        <li>artortachile@gmail.com</li>
        <li>Teléfonos:</li>
        <li>227353947</li>
        <li>+56978093790</li>
      </ul>
    </div>
  </div>
</footer>

app/views/layouts/_modal.html.erb
<div class="modal fade">
  <div class="modal-body"></div>
</div>

app/views/layouts/_search_bar.html.erb
<%= form_tag(search_path, method: 'get', class: 'search-form') do %>
  <input name="tag_list" type="text" class="search-form__bar">
  <% if use_scoped_resources? %>
    <%= select_tag :category, options_for_select(Category.where(realm: current_realm).active.map { |category| [category.name, category.slug] }), label: false, include_blank: false, class: "search-form__category" %>
  <% else %>
    <%= select_tag :category, options_for_select(Category.active.map { |category| [category.name, category.slug] }), label: false, include_blank: false, class: "search-form__category" %>
  <% end %>
  <%= submit_tag "Buscar", class: 'btn search-form__submit' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <head>
    <meta charset="utf-8"/>
    <meta content="IE=edge" http-equiv="X-UA-Compatible"/>
    <meta content="width=device-width, initial-scale=1" name="viewport"/>
    <title>Art-Torta</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'%>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
    <!--[if lt IE 9]
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    -->
  </head>
  <body>
    <div id="app">
      <navbar brand-image="<%= image_url("logo.png") %>" :links="<%= navbar_links.to_json %>"></navbar>
      <div class="content">
        <% flash.each do |name, msg| %>
          <%= content_tag :div, msg, :id => "flash_#{name}", :class => "flash" if msg.is_a?(String) %>
        <% end %>
        <%= yield %>
        <base-modal ref="modal"></base-modal>
      </div>
    </div>
    <div class="clearfix"></div>
  </body>
  <%= render "layouts/footer" %>
</html>